### ISSUE TITLE
Error getting a list of isues: 400 Bad Request

### ISSUE THREAD

**Issue by jessesquires** [lowply/auto-closer#3]
Hello! 👋🏼 

When I try to use this action, it fails with the error:

```
Error getting a list of isues: 400 Bad Request
```

This is in a private organization repo -- I'm not sure if that's a problem for the default `GITHUB_TOKEN` ?

My workflow looks like this:

```yml
jobs:
  open:
    name: Open New Meeting Agenda
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/issue-from-template
      - name: issue from template
        uses: lowply/issue-from-template@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IFT_TEMPLATE_NAME: meeting_agenda.md
  close:
    name: Close Previous Meetings
    runs-on: ubuntu-latest
    needs: open
    steps:
      # https://github.com/marketplace/actions/auto-closer
      - uses: lowply/auto-closer@v0.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AC_LABEL: "meeting agenda"
          AC_KEEP: 1
```
